SELECT BU_SID, BU_BK, BU_BK_DESCR, BU_DEPTID, TREE_NAME, EFF_DATE, 
    SETID, COMPANY, COMPANY_DESCR, COMPANY_DESCR_SHORT, LEVEL1_BK, 
    LEVEL1_NAME, LEVEL1_DEPTID, LEVEL1_DESCR, LEVEL1_DESCR_SHORT, 
    LEVEL1_EFFDT, LEVEL2_BK, LEVEL2_NAME, LEVEL2_DEPTID, LEVEL2_DESCR, 
    LEVEL2_DESCR_SHORT, LEVEL2_EFFDT, LEVEL3_BK, LEVEL3_NAME, 
    LEVEL3_DEPTID, LEVEL3_DESCR, LEVEL3_DESCR_SHORT, LEVEL3_EFFDT, LEVEL4_BK, 
    LEVEL4_NAME, LEVEL4_DEPTID, LEVEL4_DESCR, LEVEL4_DESCR_SHORT, LEVEL4_EFFDT, 
    LEVEL5_BK, LEVEL5_NAME, LEVEL5_DEPTID, LEVEL5_DESCR, LEVEL5_DESCR_SHORT, 
    LEVEL5_EFFDT, LEVEL6_BK, LEVEL6_NAME, LEVEL6_DEPTID, LEVEL6_DESCR, 
    LEVEL6_DESCR_SHORT, LEVEL6_EFFDT, LEVEL7_BK, LEVEL7_NAME, LEVEL7_DEPTID, 
    LEVEL7_DESCR, LEVEL7_DESCR_SHORT, LEVEL7_EFFDT, END_DATE, CURR_IND, 
    GL_CLIENT, GL_RESPONSE, GL_SERVICE_LN, GL_PROJECT, GL_STOB 
FROM OR_BUSINESS_UNIT_D 
WHERE CURR_IND = 'Y'
order by BU_BK, eff_date
;