SELECT "JOBCLASS_SID", "JOBCODE_BK", "JC_DESCR", "SETID", "JOBCODE", 
    "EFFDT", "JC_EFF_STATUS", "JC_DESCRSHORT", "SAL_ADMIN_PLAN", "GRADE", 
    "STEP", "UNION_CD", "STD_HOURS", "STD_HRS_FREQUENCY", "JOB_FUNCTION", 
    "JOB_FUNC_DESCR", "EMP_GROUP", "EMP_GRP_DESCR", "INCL_EXCL", "INCL_EXCL_DESCR", 
    "EFF_END_DT", "CURR_IND" 
FROM EM_JOB_CLASS_D 
WHERE "CURR_IND" = 'Y'
;