INSERT INTO EM_PAYCODE_D(
	"PAYCODE_SID",
	"PAY_CD",
	"PAY_DESCR",
	"CLASS",
	"CLASS_DESCR",
	"CODE_TYPE",
	"REDUCES_HOURS_WORKED"
) VALUES (
	ORCHESTRATE."PAYCODE_SID",
	ORCHESTRATE."PAY_CD",
	ORCHESTRATE."PAY_DESCR",
	ORCHESTRATE."CLASS",
	ORCHESTRATE."CLASS_DESCR",
	ORCHESTRATE."CODE_TYPE",
	ORCHESTRATE."REDUCES_HOURS_WORKED"
)
;