SELECT LS1.PAYRUN_ID
FROM CHIPS_LOAD_SCHED LS1
WHERE LS1.PAY_PERIOD_START_DATE = (
    SELECT MIN(LS2.PAY_PERIOD_START_DATE)
    FROM  CHIPS_LOAD_SCHED LS2
    WHERE LOAD_SKEY IS NULL
) and load_skey is null
;