SELECT 
    "APPOINTMENT_STATUS", 
    "APPT_STATUS_DESCR", 
    "APPT_DESCR_SHORT", 
    "APPOINTMENT_GROUP", 
    "APPT_GROUP_DESCR", 
    "APPT_GROUP_DESCR_SHORT", 
    "APPT_STATUS_SID" 
FROM EM_APPOINTMENT_STATUS_D
;