Insert into EM_EMPLOYEE_EMAIL_SCD (
    EMPL_SK,
    EMPLID,
    EMPL_EMAIL,
    START_PAY_PERIOD,
    END_PAY_PERIOD,
    CURRENT_FLG     
) values (
    ORCHESTRATE.EMPL_SK,
    ORCHESTRATE.EMPLID,
    ORCHESTRATE.EMPL_EMAIL,
    ORCHESTRATE.START_PAY_PERIOD,
    ORCHESTRATE.END_PAY_PERIOD,
    ORCHESTRATE.CURRENT_FLG     
);