UPDATE EM_EMPLOYEE_STATUS_D SET
	"EMPL_STATUS" = ORCHESTRATE."EMPL_STATUS",
	"DESCR" = ORCHESTRATE."DESCR",
	"EFFDT" = ORCHESTRATE."EFFDT",
	"STATUS_GRP" = ORCHESTRATE."STATUS_GRP"
WHERE "EMPL_STATUS_SID" = ORCHESTRATE."EMPL_STATUS_SID"
;