SELECT "EMPLID", "EMPL_SID", "NAME", "NID_COUNTRY", "NATIONAL_ID_TYPE", 
    "NATIONAL_ID", "NAME_PREFIX", "PREFERRED_NAME", "COUNTRY", "ADDRESS1", 
    "ADDRESS2", "ADDRESS3", "ADDRESS4", "CITY", "HOUSE_TYPE", "COUNTY", 
    "STATE", "POSTAL", "GEO_CODE", "HOME_PHONE", "WORK_PHONE", "ORIG_HIRE_DT", 
    "SEX", "BIRTHDATE", "DT_OF_DEATH", "MAR_STATUS", "DISABLED", "HIRE_DT", 
    "REHIRE_DT", "CMPNY_SENIORITY_DT", "SERVICE_DT", "EXPECTED_RETURN_DT", 
    "TERMINATION_DT", "LAST_DATE_WORKED", "BUSINESS_TITLE", "REPORTS_TO", 
    "SUPERVISOR_ID", "BUSINESS_UNIT", "DEPTID", "JOBCODE", "POSITION_NBR", 
    "EMPL_STATUS", "LOCATION", "COMPANY", "PAYGROUP", "EMPL_TYPE", "GRADE", 
    "JOBTITLE", "PHYSICAL_LOCATION" 
FROM EM_EMPLOYEE_D
;