SELECT PS.OPRID,
	PS.EMPLID,
	PS.ROWSECCLASS,
    PS.OPRDEFNDESC,
    SS.OVERRIDE_DEPTID,
    SS.DRILL_THROUGH_YN
FROM CHIPS_STG.PS_OPRDEFN_BC_TBL PS
LEFT OUTER JOIN STIIP_SECURITY_REQUIREMENT SS
    on ps.emplid=ss.emplid
WHERE PS.EMPLID IS NOT NULL
;