INSERT INTO EM_EMPLOYEE_STATUS_D(
	"EMPL_STATUS",
	"DESCR",
	"EFFDT",
	"STATUS_GRP",
	"EMPL_STATUS_SID"
) VALUES (
	ORCHESTRATE."EMPL_STATUS",
	ORCHESTRATE."DESCR",
	ORCHESTRATE."EFFDT",
	ORCHESTRATE."STATUS_GRP",
	ORCHESTRATE."EMPL_STATUS_SID"
)
;