SELECT "LOCATION_SID", "SETID_LOC", "SETID", "LOCATION", "DESCR", "DESCRSHORT", 
    "ADDRESS1", "ADDRESS2", "ADDRESS3", "ADDRESS4", "POSTAL", "CITY", 
    "REGIONAL_DISTRICT", "STATE", "COUNTRY", "COUNTRY_CODE", "EFF_DT", 
    "END_DT", "CURR_IND" 
FROM OR_LOCATION_D 
WHERE "CURR_IND" = 'Y'
;