UPDATE EM_JOB_CLASS_D SET
	"JOBCODE_BK" = ORCHESTRATE."JOBCODE_BK",
	"JC_DESCR" = ORCHESTRATE."JC_DESCR",
	"SETID" = ORCHESTRATE."SETID",
	"JOBCODE" = ORCHESTRATE."JOBCODE",
	"JC_EFF_STATUS" = ORCHESTRATE."JC_EFF_STATUS",
	"JC_DESCRSHORT" = ORCHESTRATE."JC_DESCRSHORT",
	"SAL_ADMIN_PLAN" = ORCHESTRATE."SAL_ADMIN_PLAN",
	"GRADE" = ORCHESTRATE."GRADE",
	"STEP" = ORCHESTRATE."STEP",
	"UNION_CD" = ORCHESTRATE."UNION_CD",
	"STD_HOURS" = ORCHESTRATE."STD_HOURS",
	"STD_HRS_FREQUENCY" = ORCHESTRATE."STD_HRS_FREQUENCY",
	"JOB_FUNCTION" = ORCHESTRATE."JOB_FUNCTION",
	"JOB_FUNC_DESCR" = ORCHESTRATE."JOB_FUNC_DESCR",
	"EMP_GROUP" = ORCHESTRATE."EMP_GROUP",
	"EMP_GRP_DESCR" = ORCHESTRATE."EMP_GRP_DESCR",
	"INCL_EXCL" = ORCHESTRATE."INCL_EXCL",
	"INCL_EXCL_DESCR" = ORCHESTRATE."INCL_EXCL_DESCR",
	"EFF_END_DT" = ORCHESTRATE."EFF_END_DT",
	"CURR_IND" = ORCHESTRATE."CURR_IND"
WHERE "JOBCLASS_SID" = ORCHESTRATE."JOBCLASS_SID"
;