INSERT INTO EM_STIIP_F (
    "APPOINTMENT_STATUS_SID", "LEAVE_END_DT_SK", "LEAVE_BEGIN_DT_SK", 
    "LOCATION_SID", "PAY_END_DT_SK", "EMPL_STATUS_SID", "POSITION_SID", 
    "BU_SID", "EMPL_SID", "EMPLID", "JOBCLASS_SID", "HOURLY_RATE", 
    "LEAVE_HOURS", "LEAVE_COST", "PAID_COST", "EMPL_TAKING_LEAVE", "PAYCODE_SID"
) VALUES (
    ORCHESTRATE."APPOINTMENT_STATUS_SID", ORCHESTRATE."LEAVE_END_DT_SK", 
    ORCHESTRATE."LEAVE_BEGIN_DT_SK", ORCHESTRATE."LOCATION_SID", 
    ORCHESTRATE."PAY_END_DT_SK", ORCHESTRATE."EMPL_STATUS_SID", ORCHESTRATE."POSITION_SID", 
    ORCHESTRATE."BU_SID", ORCHESTRATE."EMPL_SID", ORCHESTRATE."EMPLID", 
    ORCHESTRATE."JOBCLASS_SID", ORCHESTRATE."HOURLY_RATE", ORCHESTRATE."LEAVE_HOURS", 
    ORCHESTRATE."LEAVE_COST", ORCHESTRATE."PAID_COST", ORCHESTRATE."Empl_taking_leave", 
    ORCHESTRATE."PAYCODE_SID"
)
;