UPDATE "EM_EMPLOYEE_NAME_SCD" SET 
    "END_PAY_PERIOD"= ORCHESTRATE."END_PAY_PERIOD",
    "CURRENT_FLG"= ORCHESTRATE."CURRENT_FLG"
    WHERE "EMPL_SK"= ORCHESTRATE."EMPL_SK" 
        and "EMPLID"= ORCHESTRATE."EMPLID"
;