UPDATE OR_LOCATION_D SET
	"SETID_LOC" = ORCHESTRATE."SETID_LOC",
	"SETID" = ORCHESTRATE."SETID",
	"LOCATION" = ORCHESTRATE."LOCATION",
	"DESCR" = ORCHESTRATE."DESCR",
	"DESCRSHORT" = ORCHESTRATE."DESCRSHORT",
	"ADDRESS1" = ORCHESTRATE."ADDRESS1",
	"ADDRESS2" = ORCHESTRATE."ADDRESS2",
	"ADDRESS3" = ORCHESTRATE."ADDRESS3",
	"ADDRESS4" = ORCHESTRATE."ADDRESS4",
	"POSTAL" = ORCHESTRATE."POSTAL",
	"CITY" = ORCHESTRATE."CITY",
	"REGIONAL_DISTRICT" = ORCHESTRATE."REGIONAL_DISTRICT",
	"STATE" = ORCHESTRATE."STATE",
	"COUNTRY" = ORCHESTRATE."COUNTRY",
	"COUNTRY_CODE" = ORCHESTRATE."COUNTRY_CODE",
	"END_DT" = ORCHESTRATE."END_DT",
	"UPT_DT" = ORCHESTRATE."DSJobStartTimestamp",
	"CURR_IND" = ORCHESTRATE."CURR_IND"
WHERE "LOCATION_SID" = ORCHESTRATE."LOCATION_SID"
;