INSERT INTO EM_FTE_BURN_F (
    "APPOINTMENT_STATUS_SID", 
    "LOCATION_SID", 
    "PAY_END_DT_SK", 
    "EMPL_STATUS_SID", 
    "POSITION_SID", 
    "JOB_CLASS_SID", 
    "BU_SID", 
    "EMPLID", 
    "FTE_REG", 
    "FTE_OVT", 
    "FIRE_OVT", 
    "EMPL_SID" 
) VALUES ( 
    ORCHESTRATE."APPOINTMENT_STATUS_SID", 
    ORCHESTRATE."LOCATION_SID", 
    ORCHESTRATE."PAY_END_DT_SK", 
    ORCHESTRATE."EMPL_STATUS_SID", 
    ORCHESTRATE."POSITION_SID", 
    ORCHESTRATE."JOB_CLASS_SID", 
    ORCHESTRATE."BU_SID", 
    ORCHESTRATE."EMPLID", 
    ORCHESTRATE."FTE_REG", 
    ORCHESTRATE."FTE_OVT", 
    ORCHESTRATE."FIRE_OVT", 
    ORCHESTRATE."EMPL_SID"
)
;