MERGE INTO IRSD_BUS_PASS_CUBE target using (
    select /*+ parallel */     
        CONTACT_KEY,
        BEN_MTH_DT,
        nvl(KP_DA_CURR_PASS_COUNT,0) - nvl(LAG (KP_DA_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) "KP_DA_PASS_DIFF",
        nvl(SP_DA_CURR_PASS_COUNT,0) - nvl(LAG (SP_DA_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) "SP_DA_PASS_DIFF",
        nvl(KP_DA_CURR_CASH_COUNT,0) - nvl(LAG (KP_DA_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) "KP_DA_CASH_DIFF",
        nvl(SP_DA_CURR_CASH_COUNT,0) - nvl(LAG (SP_DA_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) "SP_DA_CASH_DIFF",
        case  
            when  nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  >  nvl(DA_CLIENT_CURR_PASS_COUNT,0)   
            and nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  =  nvl(DA_CLIENT_CURR_CASH_COUNT,0)  
            then nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  -  nvl(DA_CLIENT_CURR_PASS_COUNT,0) 
        end "PASS_CANCELLED", 
        case  
            when  nvl(DA_CLIENT_CURR_PASS_COUNT,0) > nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER ( PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  
            and nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) =   nvl(DA_CLIENT_CURR_CASH_COUNT,0)  
            then  nvl(DA_CLIENT_CURR_PASS_COUNT,0) - nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER ( PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  
        end "PASS_STARTED",
        case  
            when  nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  >  nvl(DA_CLIENT_CURR_CASH_COUNT,0)   
            and  nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  =  nvl(DA_CLIENT_CURR_PASS_COUNT,0)  
            then nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  -  nvl(DA_CLIENT_CURR_CASH_COUNT,0) 
        end "CASH_CANCELLED", 
        case  
            when  nvl(DA_CLIENT_CURR_CASH_COUNT,0) > nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER ( PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)   
            and nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER ( PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  =  nvl(DA_CLIENT_CURR_PASS_COUNT,0) 
            then nvl(DA_CLIENT_CURR_CASH_COUNT,0) - nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER ( PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) 
        end "CASH_STARTED", 
        case  
            when nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  >  nvl(DA_CLIENT_CURR_PASS_COUNT,0) 
            and  nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  <  nvl(DA_CLIENT_CURR_CASH_COUNT,0)  
            then nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  -  nvl(DA_CLIENT_CURR_PASS_COUNT,0) 
        end  "PASS_TO_CASH",
        case  
            when nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  >  nvl(DA_CLIENT_CURR_CASH_COUNT,0) 
            and nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  <  nvl(DA_CLIENT_CURR_PASS_COUNT,0) 
            then nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0)  -  nvl(DA_CLIENT_CURR_CASH_COUNT,0) 
        end "CASH_TO_PASS",
        nvl(DA_CLIENT_CURR_PASS_COUNT,0) - nvl(LAG(DA_CLIENT_CURR_PASS_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) "NET_PASS_CHANGE",
        nvl(DA_CLIENT_CURR_CASH_COUNT,0) - nvl(LAG(DA_CLIENT_CURR_CASH_COUNT) OVER (PARTITION BY CONTACT_KEY ORDER BY BEN_MTH_DT),0) "NET_CASH_CHANGE" 
    from IRSD_BUS_PASS_CUBE
) src on (
    target.BEN_MTH_DT = src.BEN_MTH_DT
    and target.CONTACT_KEY = src.CONTACT_KEY 
) 
when matched then update 
set  
    target."KP_DA_PASS_DIFF" = src."KP_DA_PASS_DIFF", 
    target."SP_DA_PASS_DIFF" = src."SP_DA_PASS_DIFF", 
    target."KP_DA_CASH_DIFF" = src."KP_DA_CASH_DIFF", 
    target."SP_DA_CASH_DIFF" = src."SP_DA_CASH_DIFF", 
    target."PASS_CANCELLED"	= src."PASS_CANCELLED", 
    target."PASS_STARTED" = src."PASS_STARTED", 
    target."CASH_CANCELLED"	= src."CASH_CANCELLED", 
    target."CASH_STARTED" = src."CASH_STARTED", 
    target."PASS_TO_CASH" = src."PASS_TO_CASH", 
    target."CASH_TO_PASS" = src."CASH_TO_PASS", 
    target."NET_PASS_CHANGE" = src."NET_PASS_CHANGE", 
    target."NET_CASH_CHANGE" = src."NET_CASH_CHANGE"