UPDATE EM_PAYCODE_D SET
	"PAY_CD" = ORCHESTRATE."PAY_CD",
	"PAY_DESCR" = ORCHESTRATE."PAY_DESCR",
	"CLASS" = ORCHESTRATE."CLASS",
	"CLASS_DESCR" = ORCHESTRATE."CLASS_DESCR",
	"CODE_TYPE" = ORCHESTRATE."CODE_TYPE",
	"REDUCES_HOURS_WORKED" = ORCHESTRATE."REDUCES_HOURS_WORKED"
WHERE "PAYCODE_SID" = ORCHESTRATE."PAYCODE_SID"
;