INSERT INTO EM_APPOINTMENT_STATUS_D (
	"APPOINTMENT_STATUS",
	"APPT_STATUS_DESCR",
	"APPT_DESCR_SHORT",
	"APPOINTMENT_GROUP",
	"APPT_GROUP_DESCR",
	"APPT_GROUP_DESCR_SHORT",
	"APPT_STATUS_SID"
) VALUES (
	ORCHESTRATE."APPOINTMENT_STATUS",
	ORCHESTRATE."APPT_STATUS_DESCR",
	ORCHESTRATE."APPT_DESCR_SHORT",
	ORCHESTRATE."APPOINTMENT_GROUP",
	ORCHESTRATE."APPT_GROUP_DESCR",
	ORCHESTRATE."APPT_GROUP_DESCR_SHORT",
	ORCHESTRATE."APPT_STATUS_SID"
)
;