SELECT "POSITION_SID", "POSITION_NBR", "POSITION_DESCR", "EFF_STATUS", "DESCRSHORT", 
    "BUDGETED_POSN", "KEY_POSITION", "REPORTS_TO", "REPORT_DOTTED_LINE", "NOC_SUB_CD", 
    "SUBCODE", "CAN_NOC_CD", "NOC", "EFF_DATE", "END_DATE", "CURR_IND" 
FROM EM_POSITION_D 
WHERE "CURR_IND" = 'Y'
;